# Generated by Django 4.2.7 on 2024-04-27 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_date', models.DateField(auto_now_add=True)),
                ('ticker', models.CharField(default='', max_length=8)),
                ('strategy', models.CharField(choices=[('1-Min ORB', '1-Min ORB'), ('5-Min ORB', '5-Min ORB'), ('ABCD', 'ABCD'), ('Reversal', 'Reversal')], default='ONEORB', max_length=12)),
                ('result', models.CharField(choices=[('Profit', 'Profit'), ('Loss', 'Loss')], default='PROFIT', max_length=6)),
                ('comments', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
