# Generated by Django 4.2.7 on 2024-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_date', models.DateField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=300)),
                ('result', models.CharField(choices=[('Profit', 'Profit'), ('Loss', 'Loss')], default='PROFIT', max_length=6)),
            ],
        ),
    ]
