# Generated by Django 4.2.7 on 2024-01-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='strategy',
            field=models.CharField(choices=[('1-Min ORB', '1-Min ORB'), ('5-Min ORB', '5-Min ORB'), ('ABCD', 'ABCD'), ('Reversal', 'Reversal')], default='ONEORB', max_length=12),
        ),
    ]
