# Generated by Django 4.2.7 on 2024-01-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entry_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
