# Generated by Django 4.2.7 on 2024-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
