# Generated by Django 4.2.7 on 2024-04-04 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0010_alter_entry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
