# Generated by Django 4.2.7 on 2024-04-14 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0015_entry_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
