# Generated by Django 4.2.7 on 2024-04-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_alter_entry_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='borrower',
        ),
    ]
