# Generated by Django 4.2.7 on 2024-04-15 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0018_remove_entry_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
