# Generated by Django 4.2.7 on 2024-04-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0019_entry_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='username',
        ),
    ]
