# Generated by Django 4.2.7 on 2024-04-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0022_alter_entry_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='username',
            new_name='trader',
        ),
    ]
